spring.application.name=gateway2
spring.application.surname=Gunel

Spring:
    application:
        name: gunel
        surname: Suleymanova


services:
    entrance: http://localhost:8088
    demo: http://localhost:8087
